In [ ]:
from tseopt import make_a_mercantile_data_object

md = make_a_mercantile_data_object()
md.update_data(timeout=20)
print(md.sandoq)
print(md.future_date_time)
print(md.markets_info)

In [ ]:
import pandas as pd

display(pd.DataFrame(md.gavahi).head(5))
# display(pd.DataFrame(md.sandoq).head(5))
# display(pd.DataFrame(md.future).head(5))
# display(pd.DataFrame(md.cdc).head(5))
# display(pd.DataFrame(md.markets_info).head(5))

Empty DataFrame
Columns: []
Index: []

In [ ]:
df = pd.DataFrame(md.markets_info)

calls = pd.DataFrame({
    # اطلاعات پایه
    'ContractCode': df['CallContractCode'],
    'ContractID': df['CallContractID'],
    # نوع قرارداد
    'Type': 'Call',

    'Description': df['CallContractDescription'],
    'LastTradingDate': df['CallLastTradingPersianDate'],
    'StrikePrice': pd.to_numeric(df['StrikePrice'], errors='coerce').fillna(0.0),
    'ContractSize': pd.to_numeric(df['CallContractSize'], errors='coerce').fillna(1.0),
    'CurrencyFa': df['CallContractCurrencyFaDesc'],
    'LastSettlementPrice': pd.to_numeric(df['CallLastSettlementPrice'], errors='coerce').fillna(0.0),
    'LastSettlementDate': df['CallLastSettlementPricePersianDate'],
    
    # اطلاعات سفارشات (Bid)
    'BidTotalVolume': pd.to_numeric(df['CallBidTotalVolume'], errors='coerce').fillna(0.0),
    'BidVolume1': pd.to_numeric(df['CallBidVolume1'], errors='coerce').fillna(0.0),
    'BidPrice1': pd.to_numeric(df['CallBidPrice1'], errors='coerce').fillna(0.0),
    
    # اطلاعات سفارشات (Ask)
    'AskTotalVolume': pd.to_numeric(df['CallAskTotalVolume'], errors='coerce').fillna(0.0),
    'AskVolume1': pd.to_numeric(df['CallAskVolume1'], errors='coerce').fillna(0.0),
    'AskPrice1': pd.to_numeric(df['CallAskPrice1'], errors='coerce').fillna(0.0),
    
    # حاشیه و حجم معاملات
    'InitialMargin': pd.to_numeric(df['CallInitialMargin'], errors='coerce').fillna(0.0),
    'RequiredMargin': pd.to_numeric(df['CallRequiredMargin'], errors='coerce').fillna(0.0),
    'TradesCount': pd.to_numeric(df['CallTradesCount'], errors='coerce').fillna(0),
    'TradesVolume': pd.to_numeric(df['CallTradesVolume'], errors='coerce').fillna(0.0),
    'TradesValue': pd.to_numeric(df['CallTradesValue'], errors='coerce').fillna(0.0),
    
    # موقعیت‌های باز
    'OpenInterests': pd.to_numeric(df['CallOpenInterests'], errors='coerce').fillna(0.0),
    'OpenInterestsChanges': pd.to_numeric(df['CallOpenInterestsChanges'], errors='coerce').fillna(0.0),
    'OpenInterestsChangesPercent': pd.to_numeric(df['CallOpenInterestsChangesPercent'], errors='coerce').fillna(0.0),
    
    # اطلاعات مشترک
    'StrikeLevel': df['StrikeLevel'],
})

puts = pd.DataFrame({
    # اطلاعات پایه
    'ContractCode': df['PutContractCode'],
    'ContractID': df['PutContractID'],
    # نوع قرارداد
    'Type': 'Put',

    'Description': df['PutContractDescription'],
    'LastTradingDate': df['PutLastTradingPersianDate'],
    'StrikePrice': pd.to_numeric(df['StrikePrice'], errors='coerce').fillna(0.0),
    'ContractSize': pd.to_numeric(df['PutContractSize'], errors='coerce').fillna(1.0),
    'CurrencyFa': df['PutContractCurrencyFaDesc'],
    'LastSettlementPrice': pd.to_numeric(df['PutLastSettlementPrice'], errors='coerce').fillna(0.0),
    'LastSettlementDate': df['PutLastSettlementPricePersianDate'],
    
    # اطلاعات سفارشات (Bid)
    'BidTotalVolume': pd.to_numeric(df['PutBidTotalVolume'], errors='coerce').fillna(0.0),
    'BidVolume1': pd.to_numeric(df['PutBidVolume1'], errors='coerce').fillna(0.0),
    'BidPrice1': pd.to_numeric(df['PutBidPrice1'], errors='coerce').fillna(0.0),
    
    # اطلاعات سفارشات (Ask)
    'AskTotalVolume': pd.to_numeric(df['PutAskTotalVolume'], errors='coerce').fillna(0.0),
    'AskVolume1': pd.to_numeric(df['PutAskVolume1'], errors='coerce').fillna(0.0),
    'AskPrice1': pd.to_numeric(df['PutAskPrice1'], errors='coerce').fillna(0.0),
    
    # حاشیه و حجم معاملات
    'InitialMargin': pd.to_numeric(df['PutInitialMargin'], errors='coerce').fillna(0.0),
    'RequiredMargin': pd.to_numeric(df['PutRequiredMargin'], errors='coerce').fillna(0.0),
    'TradesCount': pd.to_numeric(df['PutTradesCount'], errors='coerce').fillna(0),
    'TradesVolume': pd.to_numeric(df['PutTradesVolume'], errors='coerce').fillna(0.0),
    'TradesValue': pd.to_numeric(df['PutTradesValue'], errors='coerce').fillna(0.0),
    
    # موقعیت‌های باز
    'OpenInterests': pd.to_numeric(df['PutOpenInterests'], errors='coerce').fillna(0.0),
    'OpenInterestsChanges': pd.to_numeric(df['PutOpenInterestsChanges'], errors='coerce').fillna(0.0),
    'OpenInterestsChangesPercent': pd.to_numeric(df['PutOpenInterestsChangesPercent'], errors='coerce').fillna(0.0),
    
    # اطلاعات مشترک
    'StrikeLevel': df['StrikeLevel'],
})

# ترکیب نهایی
result = pd.concat([calls, puts], ignore_index=True)

# سورت
result = result.sort_values(
    ['LastTradingDate', 'Type'], ascending=[True, True]).reset_index(drop=True)
result.to_excel('df_kala.xlsx', index=False)

In [ ]:
sandoq = pd.DataFrame(md.sandoq)
print(sandoq)

Empty DataFrame
Columns: []
Index: []

دریافت دیتا به روش کتابخانه

In [ ]:
import requests
import pandas as pd
import time

url_1 = 'https://cdn.ime.co.ir/realTimeServer/negotiate'

_timestamp = str(time.time()).replace(".", "")[:13]

params_1 = {'clientProtocol': '2.1', 'connectionData': '[{"name":"marketshub"}]', '_': _timestamp}
response_1 = requests.request(method="get", url=url_1, params=params_1)
response_1.raise_for_status()
negotiate_response = response_1.json()
connection_token = negotiate_response.get("ConnectionToken")

params_2 = {'transport': 'longPolling', 'connectionToken': connection_token, '_': _timestamp}
url2 = 'https://cdn.ime.co.ir/realTimeServer/connect'
response_2 = requests.request(method="post", url=url2, params=params_2)
response_2.raise_for_status()
connect_response = response_2.json()
message_id = connect_response.get("C")

params_3 = {'clientProtocol': '2.1', 'connectionData': '[{"name":"marketshub"}]', 'transport': 'longPolling', 'connectionToken': connection_token, '_': _timestamp}
url3 = 'https://cdn.ime.co.ir/realTimeServer/start'
response_3 = requests.request(method="post", url=url3, params=params_3)
response_3.raise_for_status()
res3 = response_3.json()

params_4 = {'clientProtocol': '2.1', 'connectionData': '[{"name":"marketshub"}]', 'transport': 'longPolling', 'connectionToken': connection_token}
url4 = 'https://cdn.ime.co.ir/realTimeServer/poll'
response_4 = requests.request(method="post", url=url4, params=params_4, data=f'messageId={message_id}', timeout=20)
response_4.raise_for_status()
res4 = response_4.json()

messages = res4.get('M', [])
for record in messages:
    if record["M"] == 'updateMarketsInfo':
        a = record["A"][0]
df = pd.DataFrame(a)
df.to_excel('df_markets_info.xlsx', index=False)

In [ ]:
import requests
import pandas as pd

HEADERS  = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
PRICE_URL = "http://old.tsetmc.com/tsev2/data/MarketWatchPlus.aspx"

def get_supply_demand_data(datas):
    """
    This function takes a string input that contains the data related to the supply and demand queues, and returns a pandas data frame that has columns for the zone, the depth, the price, and the quantity of each row and each stock.
    
    Parameters:
        datas (str): A string that contains the data related to the supply and demand queues, separated by '@' and ';'.

    Returns:
        df (pd.DataFrame): A pandas data frame that has columns for the zone, the depth, the price, and the quantity of each row and each stock.
"""

    try:
        datas = datas.split('@')[3].split(';')
    except:
        return
    if len(datas) < 100 : return 
    rows = []
    for data in datas:
        sub_data = data.split(',')
        if len(sub_data) == 8 :
            rows.append(sub_data)
    if len(rows) < 100 : return 
    df = pd.DataFrame(rows)
    df.columns =['id', 'row', 2, 3, 4, 5, 6, 7]
    df.set_index(df['id'], inplace= True)
    df.drop(columns=['id'], inplace= True)
    groups = df.groupby('row')
    df1 = groups.get_group('1')
    df1.columns=['row', 'zo1', 'zd1', 'pd1', 'po1', 'qd1', 'qo1']
    df1 = df1.drop(columns=['row'])
    df1 = df1.apply(pd.to_numeric, errors='coerce')
    return df1

def get_price():
    """
    This function requests the data from a web link specified in the config file, and calls the get_supply_demand_data function to process the data related to the supply and demand queues. 
    It also separates the data related to the price data of different stocks, and returns a pandas data frame that has columns for the code, 
    the symbol, the name, the final price, the closing price, the last price, the trade volume, the trade value, the minimum price, the maximum price, the yesterday price, the EPS, the base volume, the maximum threshold, and the minimum threshold of each stock. 
    It also calculates the percentage change of the closing price and the last price from the yesterday price, and adds them as columns to the data frame.

    Parameters:
        None

    Returns:
        df (pd.DataFrame): A pandas data frame that has columns for the code, 
        the symbol, the name, the final price, the closing price, the last price, the trade volume, the trade value, the minimum price, the maximum price, the yesterday price, the EPS, the base volume, the maximum threshold, and the minimum threshold of each stock, as well as the percentage change of the closing price and the last price from the yesterday price.
    """

    try:
        datas=requests.get(PRICE_URL, headers= HEADERS, timeout= 3).text
    except:
        return
    rows_df = get_supply_demand_data(datas)
    if rows_df is None: return
    datas = datas.split(';')
    if len(datas) < 100 : return 
    all_data = {}
    for data in datas:
        sub_data = data.split(',')
        length = len(sub_data)
        if length >= 20:  # فقط داده‌های با حداقل 20 فیلد
            if length not in all_data:
                all_data[length] = []
            all_data[length].append(sub_data)
    # پیدا کردن بیشترین تعداد داده
    best_length = max(all_data.keys(), key=lambda x: len(all_data[x]))
    data_list = all_data[best_length]
    if len(data_list) < 100: return
    df = pd.DataFrame(data_list)
    # تعریف ستون‌های استاندارد
    standard_columns = [
        'id', 'code', 'symbol', 'name', 'HHMMSS', 'pf', 'pc', 'pl',
        'tno', 'tvol', 'tval', 'pmin', 'pmax', 'py', 'eps', 'bvol',
        'extra1', 'extra2', 'industry_code', 'tmax', 'tmin', 'z', 'cs', 'nav',]
    # ستون‌های اضافی برای تعداد فیلدهای بیشتر
    extra_columns = ['extra7', 'extra8', 'extra9', 'extra10']
    # ترکیب ستون‌ها
    all_columns = standard_columns + extra_columns
    # اختصاص ستون‌ها به اندازه تعداد فیلدها
    df.columns = all_columns[:len(df.columns)]

    # حذف سطرهای نامعتبر
    df = df[~df['symbol'].str.contains(r'\d')]
    # تنظیم ایندکس
    df.set_index('id', inplace=True)
    # حذف ستون‌های اضافی
    # extra_cols = [col for col in df.columns if col.startswith('extra')]
    # df.drop(columns=extra_cols, inplace=True, errors='ignore')
    # ترکیب با داده‌های صف
    df = pd.concat([df, rows_df], axis=1)
    # تبدیل به عددی
    numeric_cols = ['pf', 'pc', 'pl', 'tno', 'tvol', 'tval', 'pmin', 'pmax', 'py', 'eps', 'bvol', 'tmax', 'tmin', 'z', 'nav']
    for col in numeric_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')

    return df

price_df = get_price()
# price_df.to_excel('price_df.xlsx')
sell_queue = price_df[(price_df['pl'] == price_df['tmin']) & ((price_df['pd1'] == 0) | (price_df['pd1'] < price_df['tmin']))]
buy_queue = price_df[(price_df['pl'] == price_df['tmax']) & ((price_df['po1'] == 0) | (price_df['po1'] > price_df['tmax']))]
buy_queue

,code,symbol,name,HHMMSS,pf,pc,pl,tno,tvol,tval,...,cs,nav,extra7,extra8,zo1,zd1,pd1,po1,qd1,qo1
id,,,,,,,,,,,,,,,,,,,,,
70498485598181604,IRO3FOHZ0001,هرمز,فولاد هرمزگان جنوب,122945,3440.0,3610.0,3640.0,2402.0,199828575.0,7.213429e+11,...,303,NaN,,Z1,2,195,3640,3700,31366993,15000
56429431740318486,IRO7SHLP0001,شلرد,كود شيميايي اوره لردگان,122957,2330.0,2434.0,2474.0,1324.0,163972430.0,3.991341e+11,...,309,NaN,,P1,1,35,2474,2727,9383008,2000
54509759694064219,IRO7HPKP0001,تپكو,توليدتجهيزات‌سنگين‌هپكو,122846,489.0,498.0,503.0,1184.0,863607659.0,4.303655e+11,...,309,NaN,,P1,3,153,503,518,143231947,82000
50185721305191887,IRO1RADI0001,ختور,رادياتور ايران‌,122947,2824.0,2938.0,2998.0,505.0,56437081.0,1.657921e+11,...,300,NaN,,N1,5,42,2998,3027,5785410,9466
62258804563636993,IRO1GSKE0001,تكشا,گسترش‌صنايع‌وخدمات‌كشاورزي‌,122752,9160.0,9630.0,9710.0,769.0,14572550.0,1.403696e+11,...,300,NaN,,N2,1,35,9710,9770,956939,600
10236455588057352,IRO3EELZ0001,انتخاب,گروه انتخاب الكترونيك آرمان,163312,2052.0,2138.0,2178.0,1780.0,572073099.0,1.222833e+12,...,303,NaN,,Z1,1,37,2178,2192,28792992,2340
35331248532537562,IRO1ARDS0001,اردستان,سيمان اردستان,122922,26110.0,27370.0,27710.0,1062.0,7135108.0,1.952909e+11,...,300,NaN,,N1,2,18,27710,27890,1207057,503
63915926161403347,IRO1KHSH0001,خشرق,الكتريك‌ خودرو شرق‌,122955,2501.0,2626.0,2655.0,585.0,60340277.0,1.584621e+11,...,300,NaN,,N2,1,38,2655,2672,13782774,10000
57468269415483633,IRT1SOLA0001,سولار,صندوق راهبرد انرژي فردا-پروژه,145238,12173.0,12169.0,12173.0,422.0,13768672.0,1.675562e+11,...,305,10413.0,,HN,2,167,12173,12248,8285123,2000
59866041653103343,IRO3BNOP0001,نوين,بيمه نوين,160854,7620.0,8040.0,8070.0,480.0,14525757.0,1.168364e+11,...,303,NaN,,Z1,2,1,8040,8090,10000,2000
7711282667602555,IRO1PARK0001,شاراك,پتروشيمي شازند,122755,21930.0,22940.0,23110.0,1681.0,33540474.0,7.695619e+11,...,300,NaN,,N1,7,362,23110,25440,18717887,123502
62977319271289925,IRO3KBCZ0001,كي بي سي,شركت كي بي سي,122915,9720.0,10000.0,10320.0,2781.0,54290795.0,5.431159e+11,...,303,NaN,,Z1,3,10,10320,10330,104818,21530
59839275647597021,IRO7VOSP0001,وثوق,سرمايه گذاري وثوق امين,161352,38950.0,40280.0,40400.0,209.0,1477778.0,5.951797e+10,...,309,NaN,,P1,1,4,40400,41250,24913,1000
47348197320716810,IRO3DSNZ0001,دسانكو,داروسازي سبحان انكولوژي,122957,3030.0,3160.0,3210.0,1088.0,48959837.0,1.546350e+11,...,303,NaN,,1Z,1,10,3210,3280,497011,5000
6757220448540984,IRO1SIMS0001,سشمال,سيمان‌ شمال‌,122828,16200.0,16930.0,17200.0,720.0,11248763.0,1.904912e+11,...,300,NaN,,N1,4,20,17200,17220,399818,50323
19257295292088310,IRO1INDM0001,خكمك,كمك‌فنرايندامين‌,122922,2449.0,2559.0,2599.0,909.0,66245640.0,1.695544e+11,...,300,NaN,,N2,1,6,2599,2676,232000,1886
50580753680043015,IRO7PSMP0001,معيار,سرمايه گذاري معيار صنعت پارس,122913,2447.0,2513.0,2520.0,189.0,14941915.0,3.755191e+10,...,309,NaN,,P1,1,1,2520,2555,118630,100000
11403770140000603,IRO1VLMT0001,ولملت,واسپاري ملت,122955,19050.0,19050.0,19050.0,138.0,3434441.0,6.542610e+10,...,300,NaN,,N2,1,356,19050,19650,21680853,1951
26882843763780650,IRO7BLIP0001,باران,بيمه زندگي باران,122439,2485.0,2485.0,2485.0,11.0,594289.0,1.476808e+09,...,309,NaN,,P1,1,4,2485,2620,1612398,10000
67213778593531096,IRO7AIMP0001,وامير,گروه صنعتي و معدني امير,122958,10910.0,10910.0,10910.0,914.0,44348300.0,4.838391e+11,...,309,NaN,,P1,1,1,10640,10910,40000,60000
30443839313522574,IRO7RAHP0001,حرهشا,رهشاد سپاهان (سهامي عام,163128,27850.0,28880.0,28920.0,70.0,1103621.0,3.187272e+10,...,309,NaN,,C1,1,1,28710,28920,2000,4010
34552750623263639,IRO3PLSP0001,پلاست,كارخانجات توليدي پلاستيران,122925,2140.0,2184.0,2195.0,1082.0,126833455.0,2.770342e+11,...,303,NaN,,Z1,1,159,2195,2219,49628490,1000000
39807886630843041,IRO3BMAZ0001,بمپنا,توليد برق عسلويه مپنا,122848,7270.0,7590.0,7710.0,984.0,98630437.0,7.490129e+11,...,303,NaN,,Z1,1,86,7710,7920,21237379,4001
41350070322027412,IRT3AMTF0001,آميتيس,صندوق س.سهامي درخشان آميتيس-س,122636,27800.0,28030.0,28289.0,26.0,27187.0,7.620594e+08,...,305,28031.0,,T1,1,2,27800,28289,98025,39378
35425587644337450,IRO1MSMI0001,فملي,ملي‌ صنايع‌ مس‌ ايران‌,123003,20880.0,21880.0,22160.0,42663.0,717727575.0,1.570033e+13,...,300,NaN,,N1,1,2222,22160,29200,65244762,2400
50247622569476338,IRO1BONA0001,بوعلي,پتروشيمي بوعلي سينا,122959,43130.0,44990.0,45790.0,2656.0,14905339.0,6.705788e+11,...,300,NaN,,N1,2,166,45790,51760,1612015,4074
55959112038778737,IRO7SEKP0001,سخواف,سيمان مجد خواف,122645,5900.0,5970.0,6160.0,512.0,18195809.0,1.086274e+11,...,309,NaN,,P1,1,11,6160,6360,562811,3000
56574323121551263,IRO7PKBP0001,شكبير,پتروشيمي اميركبير,122934,121500.0,128000.0,128900.0,434.0,987509.0,1.263635e+11,...,309,NaN,,P1,9,2,128000,128900,1996,73326
6478064539164167,IRO3RPEZ0001,ريشمك,توليد و صادرات ريشمك,122550,14740.0,14750.0,14780.0,408.0,8625303.0,1.271943e+11,...,303,NaN,,1Z,2,126,14780,14940,8263429,580
8977441217024425,IRO1SEPA0001,فسپا,گروه‌صنعتي‌سپاهان‌,122734,5700.0,5990.0,6040.0,2415.0,145148594.0,8.689581e+11,...,300,NaN,,N1,1,50,6040,6080,5365936,12390
19471788163911687,IRO1NSPS0001,كفپارس,فرآورده‌هاي‌ نسوز پارس‌,122908,5030.0,5200.0,5330.0,1663.0,63747096.0,3.315313e+11,...,300,NaN,,N2,1,6,5330,5440,132439,1000
21772258644715569,IRO1PGDR0001,شغدير,پتروشيمي غدير,122912,67200.0,69930.0,70070.0,1698.0,10950087.0,7.657327e+11,...,300,NaN,,N2,1,88,70070,70080,1157132,500
26316376625263940,IRO1PYPD0001,پي پاد,پرداخت الكترونيك پاسارگاد,122951,7190.0,7440.0,7630.0,1078.0,47595568.0,3.540088e+11,...,300,NaN,,N2,1,225,7630,7650,48168787,108240
4528607775462304,IRO1SFNO0001,سفانو,سيمان فارس نو,122904,51880.0,53630.0,55080.0,649.0,1806038.0,9.685426e+10,...,300,NaN,,N1,2,20,55080,56060,70404,4090
24079409192818584,IRO1DRKH0001,پدرخش,درخشان‌ تهران‌,145025,5340.0,5550.0,5660.0,679.0,21459267.0,1.190202e+11,...,300,NaN,,N2,1,27,5660,5710,1053710,2260
28809886765682162,IRO1HSHM0001,حفاري,حفاري شمال,122908,5370.0,5610.0,5690.0,2750.0,149896991.0,8.412065e+11,...,300,NaN,,N1,2,116,5690,5800,24716765,10870
40611478183231802,IRO1DODE0001,شدوص,دوده‌ صنعتي‌ پارس‌,122833,6730.0,7040.0,7130.0,496.0,22580813.0,1.589820e+11,...,300,NaN,,N2,2,64,7130,7270,14446539,1494
48010225447410247,IRO1BANK0001,وبانك,سرمايه گذاري گروه توسعه ملي,122956,10200.0,10490.0,10700.0,2892.0,287968144.0,3.019932e+12,...,300,NaN,,N1,1,474,10700,16200,50117954,300000
54277068923045214,IRO1SORB0001,فسرب,ملي‌ سرب‌وروي‌ ايران‌,122931,2277.0,2378.0,2417.0,1620.0,109589269.0,2.606369e+11,...,300,NaN,,N2,1,30,2417,2418,4120478,2088
13243992182070788,IRO3RAPZ0001,درهآور,دارويي ره آورد تامين,122911,15420.0,16140.0,16360.0,948.0,14963814.0,2.415346e+11,...,303,NaN,,1Z,1,76,16360,16950,5129235,3000
27096851668435724,IRO1JPPC0001,جم پيلن,پتروشيمي جم پيلن,122926,248100.0,257900.0,263300.0,1485.0,2322469.0,5.989899e+11,...,300,NaN,,N2,1,9,263300,263600,10063,500
57551382352708199,IRO5GSKS0001,غگز,صنايع غذايي سكه,122923,3260.0,3350.0,3370.0,1008.0,68913924.0,2.309309e+11,...,313,NaN,,V1,1,181,3370,3640,13659929,10000
59486059679335017,IRO1PETR0001,وپترو,سرمايه‌گذاري صنايع پتروشيمي‌,122948,69100.0,72320.0,73130.0,1126.0,7688924.0,5.560869e+11,...,300,NaN,,N1,5,147,73130,105800,1746687,109500
66450490505950110,IRO1DAML0001,ددام,داروسازي زاگرس فارمد پارس,122951,11710.0,11870.0,12430.0,1038.0,66806969.0,7.931016e+11,...,300,NaN,,N2,3,63,12430,12510,1079708,105004

In [12]:
buy_queue = price_df[(price_df['pl'] == price_df['tmax']) & ((price_df['po1'] == 0) | (price_df['po1'] > price_df['tmax']))]
buy_queue.to_excel('buy_queue.xlsx')